# Generated by Django 5.0 on 2024-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_Male',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
