# Generated by Django 5.0 on 2024-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
